### ISSUE TITLE
missing dependency on "puppet" gem

### ISSUE THREAD

**Issue by pdurbin** [rodjek/puppet-lint#33]
Hello, I discovered puppet-lint via my "<a href="http://groups.google.com/group/puppet-users/browse_thread/thread/e25ddd9a7233bad0">perltidy workalike to tidy up Puppet manifests</a>" post on the puppet-users list.  There seems to be a missing dependency on the "puppet" gem:

```
[pdurbin@beamish ~]$ gem install puppet-lint
Fetching: puppet-lint-0.1.5.gem (100%)
Successfully installed puppet-lint-0.1.5
1 gem installed
Installing ri documentation for puppet-lint-0.1.5...
Installing RDoc documentation for puppet-lint-0.1.5...
[pdurbin@beamish ~]$ puppet-lint --version
/home/pdurbin/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- puppet (LoadError)
        from /home/pdurbin/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/pdurbin/.rvm/gems/ruby-1.9.2-p290/gems/puppet-lint-0.1.5/lib/puppet-lint/plugins/check_strings.rb:1:in `<top (required)>'
        from /home/pdurbin/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/pdurbin/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/pdurbin/.rvm/gems/ruby-1.9.2-p290/gems/puppet-lint-0.1.5/lib/puppet-lint/plugins.rb:8:in `<top (required)>'
        from /home/pdurbin/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/pdurbin/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/pdurbin/.rvm/gems/ruby-1.9.2-p290/gems/puppet-lint-0.1.5/lib/puppet-lint.rb:2:in `<top (required)>'
        from /home/pdurbin/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/pdurbin/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/pdurbin/.rvm/gems/ruby-1.9.2-p290/gems/puppet-lint-0.1.5/bin/puppet-lint:18:in `<top (required)>'
        from /home/pdurbin/.rvm/gems/ruby-1.9.2-p290/bin/puppet-lint:19:in `load'
        from /home/pdurbin/.rvm/gems/ruby-1.9.2-p290/bin/puppet-lint:19:in `<main>'
[pdurbin@beamish ~]$ gem install puppet
Fetching: facter-1.6.1.gem (100%)
Fetching: puppet-2.7.5.gem (100%)
Successfully installed facter-1.6.1
Successfully installed puppet-2.7.5
2 gems installed
Installing ri documentation for facter-1.6.1...
Installing ri documentation for puppet-2.7.5...
Installing RDoc documentation for facter-1.6.1...
Installing RDoc documentation for puppet-2.7.5...
[pdurbin@beamish ~]$ puppet-lint --version
Puppet-lint 0.1.5
[pdurbin@beamish ~]$ 
```

Perhaps this has to do with my RVM installation (I'm new to RVM), but I don't think so as other dependencies are usually pulled in.

**Comment by realflash** [comment]
So what's the correct approach to take, assuming I have installed puppet via my package manager and therefore don't want to install the gem? How do I tell it that the puppet binaries are really there?
