### ISSUE TITLE
Issue with puppet-lint 1.1.0 binary on lucid

### ISSUE THREAD

**Issue by melissa** [rodjek/puppet-lint#364]
When installing the puppet-lint 1.1.0 gem on lucid, I run into an undefined method error when running the binary against puppet code.
```
root@lucid:~# /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/puppet-lint puppetlabs-rpmbuilder/manifests/init.pp
/var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/data.rb:34:in `tokens': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/data.rb:99
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/data.rb:97:in `call'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/data.rb:97:in `resource_indexes'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/checkplugin.rb:74:in `resource_indexes'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/plugins/check_conditionals.rb:5:in `check'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/checkplugin.rb:21:in `run'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/checks.rb:58:in `run'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/checks.rb:56:in `each'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/checks.rb:56:in `run'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint.rb:168:in `run'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/bin.rb:59:in `run'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/bin.rb:56:in `each'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/bin.rb:56:in `run'
	from /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/puppet-lint:7
```
Since, in this instance, `caller` is a nil object, ruby doesn't know what to do when we call it in 
```
if caller[0][/`.*'/][1..-2] == 'check'
```
 on line 34. It looks like `caller` is a method provided by ruby (http://www.ruby-doc.org/core-1.8.7/Kernel.html#method-i-caller). 

Testing it out, everything else seems to work fine
```
irb(main):002:0> require 'puppet-lint'
=> true
```
```
root@lucid:~# /var/lib/gems/1.8/gems/puppet-lint-1.1.0/bin/puppet-lint --version
puppet-lint 1.1.0
```
```
root@lucid:~# ruby --version
ruby 1.8.7 (2010-01-10 patchlevel 249) [x86_64-linux]
```

I'm not running into this issue on any other platform.

**Comment by rodjek** [comment]
This has been fixed in master (I've been testing against a newer 1.8.7 patch number and it looks like the output of Kernel#caller changed between p249 and p358) and we be part of the next release.
