### ISSUE TITLE
puppet-lint failure for resource declarations with colons followed by non-whitespaces

### ISSUE THREAD

**Issue by sandra-thieme** [rodjek/puppet-lint#370]
If a resource declaration's colon is followed by anything that's not a whitespace puppet-lint fails with the following exception:

```
/var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:115:in `[]': no implicit conversion from nil to integer (TypeError)
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:115:in `block (2 levels) in check'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:111:in `each'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:111:in `each_with_index'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:111:in `block in check'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:95:in `each'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:95:in `check'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/checkplugin.rb:21:in `run'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:58:in `block in run'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:56:in `each'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:56:in `run'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:168:in `run'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:59:in `block in run'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `each'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `run'
    from /var/lib/gems/1.9.1/gems/puppet-lint-1.1.0/bin/puppet-lint:7:in `<top (required)>'
    from /usr/local/bin/puppet-lint:23:in `load'
    from /usr/local/bin/puppet-lint:23:in `<main>'
```

This example fails:

```
class foo {
  file {'/tmp/foobar': ensure => present,
    owner => 'user',
  }
}
```

But this doesn't fail:

```
class foo {
  file {'/tmp/foobar': ensure => present,
  }
}
```

**Comment by rj667** [comment]
Issue #339 is now closed without fixing this bug. I guess this issue wasn't a duplicate after all.
Can it be reopened?
