### ISSUE TITLE
Trailing blank lines discarded in PuppetLinter::Data.manifest_lines

### ISSUE THREAD

**Issue by jds** [rodjek/puppet-lint#378]
In writing a check for whitespace style, I came across a bug where trailing blank lines were being discarded in manifest_lines, which causes an exception to be raised when puppet-lint tries to report issues with those lines.

TL;DR: In `checks.rb` on line 23, changing `content.split("\n")` to `content.split("\n", -1)` fixes this issue.

example.pp:

```puppet

```

(Just an empty file with a newline.)

example.rb:

```ruby
PuppetLint.new_check(:example) do
  def check
    notify :error, {
      :message => 'this blows up',
      :line    => 1,
      :column  => 0,
    }
  end
end
```

```console
% puppet-lint --load example.rb --only-checks example --with-context example.pp
ERROR: this blows up on line 1
lib/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:118:in `print_context': undefined method `index' for nil:NilClass (NoMethodError)
	from lib/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:138:in `block in report'
	from lib/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:130:in `each'
	from lib/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:130:in `report'
	from lib/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:178:in `print_problems'
	from lib/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:60:in `block in run'
	from lib/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `each'
	from lib/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `run'
	from lib/ruby/1.9.1/gems/puppet-lint-1.1.0/bin/puppet-lint:7:in `<top (required)>'
	from bin/puppet-lint:16:in `load'
	from bin/puppet-lint:16:in `<main>'
```

Adding `puts PuppetLint::Data.manifest_lines.inspect` on line 24 of `checks.rb` shows:

```console
% puppet-lint --load example.rb --only-checks example --with-context example.pp
[]
ERROR: this blows up on line 1
lib/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:118:in `print_context': undefined method `index' for nil:NilClass (NoMethodError)
<...same error...>
```

The root cause is Ruby's [stripping trailing nulls](http://www.ruby-doc.org/core-2.2.0/String.html#method-i-split) (link is to 2.2.0 but behavior is the same in 1.9.1).

Changing `content.split("\n")` to `content.split("\n", -1)` in `checks.rb` gives the expected result:

```console
% puppet-lint --load example.rb --only-checks example --with-context example.pp

ERROR: this blows up on line 1

  
^

```

**Comment by rodjek** [comment]
Thanks, fixed! :)
