### ISSUE TITLE
crashing puppet-lint 1.1.0

### ISSUE THREAD

**Issue by drboldt** [rodjek/puppet-lint#409]
```
% cat ~/bad-lint.pp
node /^host/ {
  class {'test':
a => 'abc',
    b => $b,
  }
}

puppet-lint ~/bad-lint.pp
/opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/plugins/check_whitespace.rb:115:in `[]': no implicit conversion from nil to integer (TypeError)
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/plugins/check_whitespace.rb:115:in `check'
        from /opt/csw/lib/ruby/1.8/optparse.rb:1469:in `each_with_index'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/plugins/check_whitespace.rb:111:in `each'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/plugins/check_whitespace.rb:111:in `each_with_index'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/plugins/check_whitespace.rb:111:in `check'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/plugins/check_whitespace.rb:95:in `each'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/plugins/check_whitespace.rb:95:in `check'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/checkplugin.rb:21:in `run'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/checks.rb:58:in `run'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/checks.rb:56:in `each'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/checks.rb:56:in `run'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint.rb:168:in `run'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/bin.rb:59:in `run'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/bin.rb:56:in `each'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/../lib/puppet-lint/bin.rb:56:in `run'
        from /opt/csw/lib/ruby/gems/1.8/gems/puppet-lint-1.1.0/bin/puppet-lint:7
        from /opt/csw/bin/puppet-lint:19:in `load'
        from /opt/csw/bin/puppet-lint:19

% uname -a
SunOS natalogb 5.10 Generic_150400-20 sun4u sparc SUNW,Netra-T12
```

**Comment by drboldt** [comment]
White space (indenting) disappears when viewing issue, but is critical to error. Cannot attach puppet file. Let me know if I need to send Puppet file in a separate mode.

**Comment by labranch** [comment]
I'm getting same error.
$ uname -a
Linux xxx.xxx.com 2.6.32-431.11.2.el6.x86_64 #1 SMP Mon Mar 3 13:32:45 EST 2014 x86_64 x86_64 x86_64 GNU/Linux

$ ruby -v
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
