### ISSUE TITLE
NameError: uninitialized constant VARIABLE_TYPES

### ISSUE THREAD

**Issue by walls00000** [rodjek/puppet-lint#538]
Compatibility with puppet-lint-variable_contains_upcase-1.0.1 is broken in versions > 2.0

Here is the output from a lint run with puppet-lint-variable_contains_upcase-1.0.1:
```
** Invoke lint (first_time)
** Execute lint
rake aborted!
NameError: uninitialized constant VARIABLE_TYPES
vendor/gems/ruby/2.0.0/gems/puppet-lint-variable_contains_upcase-1.0.1/lib/puppet-lint/plugins/variable_contains_upcase.rb:4:in `block in check'
vendor/gems/ruby/2.0.0/gems/puppet-lint-variable_contains_upcase-1.0.1/lib/puppet-lint/plugins/variable_contains_upcase.rb:3:in `select'
vendor/gems/ruby/2.0.0/gems/puppet-lint-variable_contains_upcase-1.0.1/lib/puppet-lint/plugins/variable_contains_upcase.rb:3:in `check'
vendor/gems/ruby/2.0.0/gems/puppet-lint-2.0.2/lib/puppet-lint/checkplugin.rb:21:in `run'
vendor/gems/ruby/2.0.0/gems/puppet-lint-2.0.2/lib/puppet-lint/checks.rb:58:in `block in run'
vendor/gems/ruby/2.0.0/gems/puppet-lint-2.0.2/lib/puppet-lint/checks.rb:56:in `each'
vendor/gems/ruby/2.0.0/gems/puppet-lint-2.0.2/lib/puppet-lint/checks.rb:56:in `run'
vendor/gems/ruby/2.0.0/gems/puppet-lint-2.0.2/lib/puppet-lint.rb:174:in `run'
vendor/gems/ruby/2.0.0/gems/puppet-lint-2.0.2/lib/puppet-lint/tasks/puppet-lint.rb:79:in `block (3 levels) in define'
vendor/gems/ruby/2.0.0/gems/puppet-lint-2.0.2/lib/puppet-lint/tasks/puppet-lint.rb:77:in `each'
vendor/gems/ruby/2.0.0/gems/puppet-lint-2.0.2/lib/puppet-lint/tasks/puppet-lint.rb:77:in `block (2 levels) in define'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/file_utils_ext.rb:58:in `verbose'
vendor/gems/ruby/2.0.0/gems/puppet-lint-2.0.2/lib/puppet-lint/tasks/puppet-lint.rb:71:in `block in define'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `call'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
vendor/gems/ruby/2.0.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
vendor/gems/ruby/2.0.0/bin/rake:23:in `load'
vendor/gems/ruby/2.0.0/bin/rake:23:in `<top (required)>'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:63:in `load'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:24:in `run'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/cli.rb:304:in `exec'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/cli.rb:11:in `start'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/exe/bundle:27:in `block in <top (required)>'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/gems/bundler-1.12.4/exe/bundle:19:in `<top (required)>'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/bin/bundle:23:in `load'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/bin/bundle:23:in `<main>'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/bin/ruby_executable_hooks:15:in `eval'
.rvm/gems/ruby-2.0.0-p643@rails3tutorial2ndEd/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => lint
```

**Comment by rnelson0** [comment]
@walls00000 Do you have an example of a repo that is using this, that we can replicate with? If you cannot share the repo, can you share the Gemfile/Rakefile and any other configuration in use?

Also, have you done any research to ensure the problem is not with the check rather than puppet-lint, so we do not replicate those efforts? Thanks.

**Comment by rnelson0** [comment]
This is related to https://github.com/fiddyspence/puppetlint-variablecase/pull/6, you will need to pin to puppet-lint 2.0.0 or encourage @fiddyspence to release that fix in a gem.
