### ISSUE TITLE
Remove formatting with `linenumber`

### ISSUE THREAD

**Issue by rski** [rodjek/puppet-lint#539]
As pointed out [here](https://github.com/flycheck/flycheck/issues/1050), formatting the output with `linenumber` has been deprecated since two years ago and `line` has been available since v1.0.0. 
It might be time to remove `linenumber`.

**Comment by rnelson0** [comment]
I'm down with that. I'm not sure if that's acceptable for 2.1.0, since it was marked deprecated in 1.x, or if we should wait for 3.0.0. Either way, I think we should wait for flycheck to receive its fix, first. @rski please keep us apprised of that effort, and in the meantime we can discuss how quickly we can deprecate it.

**Comment by rski** [comment]
Ah, the joys of semver ~.~
2.0.0 would've been a good time to remove this, but I only just ran into it. I can leave this open and rebase once 3.0.0 is to be released.

**Comment by rnelson0** [comment]
Heh, indeed. I do think we will have a 3.x soonish regardless, as p3/Ruby 1.8.7 support disappears, so I will tag this appropriately.

**Comment by cdenneen** [comment]
@rnelson0 I think there is something still using this. If this was tagged as for 3.x why is it merged in 2.x?

```
Using puppet-lint 2.0.2 from https://github.com/rodjek/puppet-lint.git (at master@b02628a)
Installing puppet-lint-absolute_classname-check 0.2.4
Installing puppet-lint-empty_string-check 0.2.2
Installing puppet-lint-leading_zero-check 0.1.1
Installing puppet-lint-roles_and_profiles-check 0.1.1
Installing puppet-lint-undef_in_function-check 0.2.1
Installing puppet-lint-unquoted_string-check 0.3.0
Installing puppet-lint-variable_contains_upcase 1.0.2
Installing puppet 4.3.2


+ echo Running Lint Testing
Running Lint Testing
+ bundle exec rake lint
rake aborted!
KeyError: key{linenumber} not found
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint.rb:102:in `%'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint.rb:102:in `format_message'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint.rb:136:in `block in report'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint.rb:130:in `each'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint.rb:130:in `report'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint.rb:183:in `print_problems'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint/tasks/puppet-lint.rb:80:in `block (3 levels) in define'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint/tasks/puppet-lint.rb:77:in `each'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint/tasks/puppet-lint.rb:77:in `block (2 levels) in define'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-b02628af003d/lib/puppet-lint/tasks/puppet-lint.rb:71:in `block in define'
/home/jenkins-slave/workspace/infra-controltemplate-validate/.bundle/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/cli.rb:332:in `exec'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/cli.rb:11:in `start'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/exe/bundle:34:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.1.8/gems/bundler-1.13.0/exe/bundle:26:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.8/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.1.8/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => lint
(See full trace by running task with --trace)
Build step 'Execute shell' marked build as failure
```

**Comment by rski** [comment]
@cdenneen It's not released with 2.x though, master is ahead of 2.x and 3.x could be cut from it any time. 
```
Using puppet-lint 2.0.2 from https://github.com/rodjek/puppet-lint.git (at master@b02628a)
```
This seems misleading because puppet-lint 2.0.2 was released at https://github.com/rodjek/puppet-lint/commit/9bf6d30254a005f845ecd8e6e6be23e614935788 and b02628a is the current tip of master.

**Comment by cdenneen** [comment]
@rski you are correct, i read the `2.0.2` and missed the `master`,... but then something in puppet-lint master is still using linenumber even with this merged, correct?

**Comment by rski** [comment]
yup. You can probably track it down and fix it quite easily :). Until then pinning puppet-lint to 2.0.2 should work.

**Comment by rnelson0** [comment]
I am guessing it is a plugin using it. Regardless, you should either not point to github and use gem versions, or point to github/HEAD and accept that breakage may happen as you'll be using some unreleased code. We appreciate those testing against HEAD but certainly recommend you be able to drop to a pinned version in a hurry when the breakage starts to affect you.
