### ISSUE TITLE
Puppet-Lint Issue - Error enclosed

### ISSUE THREAD

**Issue by mikebbb** [rodjek/puppet-lint#699]
---
puppet-lint version: 2.2.1
ruby version: 2.0.0-p648
platform: universal.x86_64-darwin16
file path: /Users/mikeb/Documents/WorkTransfer/Puppet4/Repro/code/environments/production/modules/helloworld/manifests/init.pp
file contents:
```
 #Helloworld class
 class helloworld
   ( $server = 'Unknown'){
   notify { 'Say hello':
     message => "Hello from ${server},
   }
 }

```
error:
```
TypeError: no implicit conversion of nil into String
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/lib/puppet-lint/lexer.rb:299:in `+'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/lib/puppet-lint/lexer.rb:299:in `slurp_string'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/lib/puppet-lint/lexer.rb:206:in `tokenise'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:25:in `load_data'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:53:in `run'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/lib/puppet-lint.rb:191:in `run'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/lib/puppet-lint/bin.rb:59:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/lib/puppet-lint/bin.rb:56:in `each'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/lib/puppet-lint/bin.rb:56:in `run'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.2.1/bin/puppet-lint:7:in `<top (required)>'
/usr/local/bin/puppet-lint:22:in `load'
/usr/local/bin/puppet-lint:22:in `<main>'

**Comment by rnelson0** [comment]
puppet-lint should only be run against files that can be validated by puppet:
```
$ puppet parser validate test.pp
Error: Could not parse for environment production: Unclosed quote after 'server' followed by ',\n  }...' at /home/rnelson0/test.pp:5:37
```

Currently, it's up to you to determine that ahead of time or puppet-lint may crash when quotes and blocks are open ended. This will be addressed in the v3.0 milestone. Thanks!
