### ISSUE TITLE
NoMethodError: undefined method `next_token' for nil:NilClass

### ISSUE THREAD

**Issue by SimonHoenscheid** [rodjek/puppet-lint#705]
puppet-lint version: 2.2.1
ruby version: 2.1.9-p490
platform: x86_64-darwin16.0
file path: /Volumes/Daten/coderepositories/puppet4/modules/modulename/manifests/syslogclient.pp
file contents:
```
# modulename remote syslogging stuff
class modulename::syslogclient (
  $enable_remote_syslog   = hiera('modulename::syslogclient::enable_remote_syslog', true),
  $remote_syslog_host     = hiera('modulename::syslogclient::remote_syslog_host', 'localhost'),
  $remote_syslog_port     = hiera('modulename::syslogclient::remote_syslog_port', '514'),
  $remote_syslog_protocol = hiera('modulename::syslogclient::remote_syslog_protocol', 'udp'),

){
  if $enable_remote_syslog {
    class{'rsyslog::client':
      remote_servers => [
      {
        host      =>  $remote_syslog_host,
        port      =>  $remote_syslog_port,
        protocol  =>  $remote_syslog_protocol,
      },
    }
  }
}

```
error:
```
NoMethodError: undefined method `next_token' for nil:NilClass
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/lexer/token.rb:180:in `find_token_of'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/lexer/token.rb:122:in `next_token_of'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/data.rb:115:in `block in resource_indexes'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/data.rb:111:in `each'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/data.rb:111:in `resource_indexes'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checkplugin.rb:74:in `resource_indexes'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/plugins/check_conditionals.rb:7:in `check'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checkplugin.rb:21:in `run'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:58:in `block in run'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:56:in `each'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:56:in `run'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint.rb:191:in `run'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/bin.rb:59:in `block in run'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/bin.rb:56:in `each'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/lib/puppet-lint/bin.rb:56:in `run'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.2.1/bin/puppet-lint:7:in `<top (required)>'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/bin/puppet-lint:23:in `load'
/Users/simonhoenscheid/.rbenv/versions/2.1.9/bin/puppet-lint:23:in `<main>'
```

**Comment by SimonHoenscheid** [comment]
Missed the closing bracket of the array. Adding this fixes the error
