### ISSUE TITLE
Check Whitespace - Undefined method 'each' for nil:NilClass

### ISSUE THREAD

**Issue by warmfusion** [rodjek/puppet-lint#710]
Trying to configure a RunDeck module via Puppet, and getting an exception thrown by the check_whitespace system.

# Test Case

``` 
class my_test_class {
  class { '::rundeck':
    $api_policies = [
      {
        'description' => 'API project level access control',
        'context' => {
          'project' => '.*',
        },
        'for' => {
          'resource' => [
            { 'equals' => {'kind' => 'job'}, 'allow' => '*' },
            { 'equals' => {'kind' => 'node'}, 'allow' => '*' },
            { 'equals' => {'kind' => 'event'}, 'allow' => '*' }
          ],
          'adhoc' => [
            {'allow' => '*'}
          ],
          'node' => [
            {'allow' => '*'}
          ],
        },
        'by' => [{
          'group' => ['api_token_group']
        }]
      },
      {
        'description' => 'API Application level access control',
        'context' => {
          'application' => 'rundeck',
        },
        'for' => {
          'resource' => [
            { 'equals' => {'kind' => 'system'}, 'allow' => '*' }
          ],
          'project' => [
            { 'match' => {'name' => '.*'}, 'allow' => '*' }
          ],
          'storage' => [
            { 'match' => {'path' => '(keys|keys/.*)'}, 'allow' => '*' },
          ],
        },
        'by' => [{
          'group' => ['api_token_group']
        }]
      }
    ]
  }
}
```

## Stack Trace
```
/Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/plugins/check_whitespace.rb:181:in `block (2 levels) in check': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/plugins/check_whitespace.rb:144:in `each'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/plugins/check_whitespace.rb:144:in `each_with_index'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/plugins/check_whitespace.rb:144:in `block in check'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/plugins/check_whitespace.rb:127:in `each'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/plugins/check_whitespace.rb:127:in `check'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/checkplugin.rb:21:in `run'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/checks.rb:58:in `block in run'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/checks.rb:56:in `each'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/checks.rb:56:in `run'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint.rb:191:in `run'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/bin.rb:59:in `block in run'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/bin.rb:56:in `each'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/lib/puppet-lint/bin.rb:56:in `run'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/gems/puppet-lint-2.1.1/bin/puppet-lint:7:in `<top (required)>'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/bin/puppet-lint:23:in `load'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/bin/puppet-lint:23:in `<main>'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tjackson/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by warmfusion** [comment]
Sorry.

My mistake - Totally forgotten how to properly parameterise classes from puppet directly rather than hiera like I normally do.

The correct approach below resolve the issue entierly. Sorry for the bug spam.

```
  class { '::rundeck':
    api_policies => [
      {
```
