### ISSUE TITLE
invalid byte sequence in UTF-8 in selmodule-example.pp

### ISSUE THREAD

**Issue by jessereynolds** [rodjek/puppet-lint#714]
From https://travis-ci.org/jessereynolds/puppet_agent_cleanser/builds/244857482

Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.

---
puppet-lint version: 2.2.1
ruby version: 2.2.0-p0
platform: x86_64-linux
file path: vendor/bundle/ruby/2.2.0/gems/puppet-4.10.4/spec/unit/provider/selmodule-example.pp
file contents:
```
ï¿½ï¿½|ï¿½ï¿½Nï¿½ï¿½|ï¿½SE Linux Modulenagios1.5.0@00$netlink_audit_socketnlmsg_relay
appendbindconnectcreatewriterelabel

```
error:
```
ArgumentError: invalid byte sequence in UTF-8
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:23:in `split'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:23:in `load_data'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:53:in `run'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/puppet-lint-2.2.1/lib/puppet-lint.rb:191:in `run'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/puppet-lint-2.2.1/lib/puppet-lint/tasks/puppet-lint.rb:79:in `block (3 levels) in define'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/puppet-lint-2.2.1/lib/puppet-lint/tasks/puppet-lint.rb:77:in `each'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/puppet-lint-2.2.1/lib/puppet-lint/tasks/puppet-lint.rb:77:in `block (2 levels) in define'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/file_utils_ext.rb:58:in `verbose'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/puppet-lint-2.2.1/lib/puppet-lint/tasks/puppet-lint.rb:71:in `block in define'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/travis/build/jessereynolds/puppet_agent_cleanser/Rakefile:30:in `block (2 levels) in <top (required)>'
/home/travis/build/jessereynolds/puppet_agent_cleanser/Rakefile:29:in `each'
/home/travis/build/jessereynolds/puppet_agent_cleanser/Rakefile:29:in `block in <top (required)>'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
/home/travis/build/jessereynolds/puppet_agent_cleanser/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<main>'
```

**Comment by rnelson0** [comment]
This is as expected, as that file is a SELinux policy. You need to exclude that from your puppet-lint target.

**Comment by jessereynolds** [comment]
@rnelson0 Yep, sorry I should have put more details in. This is the error I always get when setting up a new module, before adding the vendor dir to the exclude list. I guess this is ultimately a bug with `puppet module generate`. Perhaps puppet-lint should say something like "If you think this is a bug please log an issue at ... "
