### ISSUE TITLE
ArgumentError: negative argument

### ISSUE THREAD

**Issue by JHoelzel** [rodjek/puppet-lint#723]
Hey,
the latest puppet-lint on Windows returns the following for me when trying to run it with --fix.

Without the --fix it runs just wunderfull =)

best,
Joe

````
error:
```
ArgumentError: negative argument
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/arrow_alignment.rb:104:in `*'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/arrow_alignment.rb:104:in `fix'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:41:in `block in fix_problems'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:38:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:38:in `fix_problems'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:61:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:191:in `run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:61:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/bin/puppet-lint:7:in `<top (required)>'
C:/Ruby23-x64/bin/puppet-lint:22:in `load'
C:/Ruby23-x64/bin/puppet-lint:22:in `<main>'
````

**Comment by JHoelzel** [comment]
i solved this through the help of this comment: https://github.com/rodjek/puppet-lint/issues/366#issuecomment-67316903  by chaning line 104 to 
`new_ws = ' ' * new_ws_len unless new_ws_len < 1`

but then it went on to:
````
error:
```
NoMethodError: undefined method `include?' for nil:NilClass
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/hard_tabs.rb:10:in `block in check'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/hard_tabs.rb:9:in `select'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/hard_tabs.rb:9:in `check'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:21:in `run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:58:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:191:in `run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:61:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.0/bin/puppet-lint:7:in `<top (required)>'
C:/Ruby23-x64/bin/puppet-lint:22:in `load'
C:/Ruby23-x64/bin/puppet-lint:22:in `<main>'
````

i think this may be related to my setup but i will keep posting solutions as far as i can
