### ISSUE TITLE
puppet lint config log_format not working

### ISSUE THREAD

**Issue by cdenneen** [rodjek/puppet-lint#725]
Tried latest release and getting bad log formatting.
Narrowed down the issue between 2.0.2 and 2.1.0 but I know that's a lot of changes @binford2k @rnelson0 

Here is example showing the issues for me:

```
 ~/src/gitlab/puppet/modulesync_configs/modules/puppet-profile_base  dev ●  be rake lint
%{filename} - %{path}:%{linenumber}:%{check}:%{KIND}:%{message}

  ]
       ^

%{filename} - %{path}:%{linenumber}:%{check}:%{KIND}:%{message}

  'set inet_protocols ipv4'
                                 ^

The latest bundler is 1.15.2, but you are currently running 1.15.1.
To update, run `gem install bundler`
 ~/src/gitlab/puppet/modulesync_configs/modules/puppet-profile_base  dev ●  bundle list | grep puppet-lint
  * puppet-lint (2.1.0)
  * puppet-lint-absolute_classname-check (0.2.4)
  * puppet-lint-classes_and_types_beginning_with_digits-check (0.1.2)
  * puppet-lint-empty_string-check (0.2.2)
  * puppet-lint-leading_zero-check (0.1.1)
  * puppet-lint-trailing_comma-check (0.3.2)
  * puppet-lint-undef_in_function-check (0.2.1)
  * puppet-lint-unquoted_string-check (0.3.0)
  * puppet-lint-variable_contains_upcase (1.2.0)
  * puppet-lint-version_comparison-check (0.2.1)
 ~/src/gitlab/puppet/modulesync_configs/modules/puppet-profile_base  dev ●  vi Gemfile
 ~/src/gitlab/puppet/modulesync_configs/modules/puppet-profile_base  dev ●  bu puppet-lint
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies....
Using rake 12.0.0
Using metaclass 0.0.4
Using puppet-lint 2.0.2 (was 2.1.0)
Using rspec-support 3.6.0
Using diff-lcs 1.3
Using CFPropertyList 2.2.8
Using json 1.8.6
Using stomp 1.4.4
Using systemu 2.6.5
Using fast_gettext 1.1.0
Using locale 2.1.2
Using text 1.3.1
Using hiera 3.4.0
Using json_pure 1.8.6
Using addressable 2.4.0
Using spdx-licenses 1.1.0
Using unf_ext 0.0.7.4
Using mime-types 2.99.3
Using netrc 0.11.0
Using redcarpet 3.4.0
Using docile 1.1.5
Using simplecov-html 0.10.1
Using tins 1.15.0
Using thor 0.19.4
Using ansi 1.5.0
Using hirb 0.7.3
Using concurrent-ruby 1.0.5
Using i18n 0.8.6
Using minitest 5.10.2
Using thread_safe 0.3.6
Using multipart-post 2.0.0
Using multi_json 1.12.1
Using retriable 2.1.0
Using parallel 1.11.2
Using bundler 1.15.1
Using puppet-syntax 2.4.1
Using rainbow 2.2.2
Using mocha 1.2.1
Using puppet-lint-absolute_classname-check 0.2.4
Using puppet-lint-leading_zero-check 0.1.1
Using puppet-lint-trailing_comma-check 0.3.2
Using puppet-lint-version_comparison-check 0.2.1
Using puppet-lint-classes_and_types_beginning_with_digits-check 0.1.2
Using puppet-lint-unquoted_string-check 0.3.0
Using puppet-lint-variable_contains_upcase 1.2.0
Using puppet-lint-empty_string-check 0.2.2
Using puppet-lint-undef_in_function-check 0.2.1
Using rspec-core 3.6.0
Using rspec-expectations 3.6.0
Using rspec-mocks 3.6.0
Using facter 2.5.0 (universal-darwin)
Using jgrep 1.4.1
Using mcollective-client 2.11.0
Using gettext 3.2.3
Using json-schema 2.8.0
Using unf 0.1.4
Using simplecov 0.14.1
Using term-ansicolor 1.6.0
Using tzinfo 1.2.3
Using faraday 0.12.1
Using parallel_tests 2.14.2
Using rspec 3.6.0
Using faraday-http-cache 2.0.0
Using facterdb 0.3.11
Using domain_name 0.5.20170404
Using simplecov-console 0.4.2
Using coveralls 0.8.21
Using activesupport 5.1.2
Using gettext-setup 0.26
Using sawyer 0.8.1
Using rspec-puppet 2.6.4
Using http-cookie 1.0.3
Using puppet 4.10.4 (universal-darwin)
Using octokit 4.7.0
Using puppetlabs_spec_helper 2.1.5
Using rest-client 1.8.0
Using rspec-puppet-facts 1.8.0
Using metadata-json-lint 2.0.1
Using github_changelog_generator 1.14.3
Using rspec-puppet-utils 3.4.0
Using puppet-blacksmith 3.4.0
Bundle updated!
Gems in the groups development and system_tests were not installed.
The latest bundler is 1.15.2, but you are currently running 1.15.1.
To update, run `gem install bundler`
 ~/src/gitlab/puppet/modulesync_configs/modules/puppet-profile_base  dev ●  bundle list | grep puppet-lint
  * puppet-lint (2.0.2)
  * puppet-lint-absolute_classname-check (0.2.4)
  * puppet-lint-classes_and_types_beginning_with_digits-check (0.1.2)
  * puppet-lint-empty_string-check (0.2.2)
  * puppet-lint-leading_zero-check (0.1.1)
  * puppet-lint-trailing_comma-check (0.3.2)
  * puppet-lint-undef_in_function-check (0.2.1)
  * puppet-lint-unquoted_string-check (0.3.0)
  * puppet-lint-variable_contains_upcase (1.2.0)
  * puppet-lint-version_comparison-check (0.2.1)
 ~/src/gitlab/puppet/modulesync_configs/modules/puppet-profile_base  dev ●  be rake lint
linux.pp - manifests/linux.pp:87:trailing_comma:WARNING:missing trailing comma after last element

  ]
   ^

linux.pp - manifests/linux.pp:86:trailing_comma:WARNING:missing trailing comma after last element

  'set inet_protocols ipv4'
                           ^

The latest bundler is 1.15.2, but you are currently running 1.15.1.
To update, run `gem install bundler`
```

**Comment by cdenneen** [comment]
If you don't try to override the `log_format` then all versions after 2.0.2 work fine... it's just the override:

```
PuppetLint.configuration.log_format = '%{path}:%{line}:%{check}:%{KIND}:%{message}'
```

**Comment by cdenneen** [comment]
I've tried reviewing the 2.0.2 -> 2.1.0 changes and don't see a redherring

**Comment by binford2k** [comment]
I think that we identified this as being the `linenumber` deprecation. For unknown reasons, @cdenneen got a silent error instead of an actual failure. I see the proper error, so I'm going to close this unless we can get a reproducible test case.

```
✔ /tmp/foomod (2.3.3@plint)
10:46 $ rake lint
rake aborted!
KeyError: key{linenumber} not found
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:103:in `%'
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:103:in `format_message'
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:152:in `block in report'
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:142:in `each'
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:142:in `report'
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:201:in `print_problems'
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint/tasks/puppet-lint.rb:84:in `block (3 levels) in define'
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint/tasks/puppet-lint.rb:81:in `each'
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint/tasks/puppet-lint.rb:81:in `block (2 levels) in define'
/Users/ben/.rvm/gems/ruby-2.3.3@plint/gems/puppet-lint-2.3.0/lib/puppet-lint/tasks/puppet-lint.rb:75:in `block in define'
Tasks: TOP => lint
(See full trace by running task with --trace)
```
