### ISSUE TITLE
NoMethodError: undefined method `type' for nil:NilClass

### ISSUE THREAD

**Issue by baurmatt** [rodjek/puppet-lint#732]
puppet-lint version: 2.3.0
ruby version: 2.3.1-p112
platform: x86_64-darwin15
file path: server-lint-test.pp
file contents:
```
# Class: sys11icinga2::server
class sys11icinga2::server (
) {
  ##
  ## Install the nagios-nrpe-plugin
  ##
  package { 'nagios-nrpe-plugin':
    ensure => 'installed',
  }
}

```
error:
```
NoMethodError: undefined method `type' for nil:NilClass
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-trailing_newline-check-1.1.0/lib/puppet-lint/plugins/check_trailing_newline.rb:5:in `check'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:21:in `run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:58:in `block in run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `each'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:191:in `run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:61:in `block in run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `each'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/bin/puppet-lint:7:in `<top (required)>'
/Users/mbaur/.rvm/gems/ruby-2.3.1/bin/puppet-lint:23:in `load'
/Users/mbaur/.rvm/gems/ruby-2.3.1/bin/puppet-lint:23:in `<main>'
/Users/mbaur/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/mbaur/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rnelson0** [comment]
I cannot reproduce this. Are there any non-printing characters or oddities in trailing spaces/newlines that aren't easily visible in markdown that may be affecting this?

**Comment by baurmatt** [comment]
Ha, yeah seems like it:

```
mbaur@mbaur(2017-08-23 10:06:16)  /tmp/sys11icigna2/manifests
$ cat -A server.pp
# Class: sys11icinga2::server$
class sys11icinga2::server ($
) {$
  ##$
  ## Install the nagios-nrpe-plugin$
  ##$
  package {M-BM- 'nagios-nrpe-plugin':$
    ensure => 'installed',$
  }$
}$
```

**Comment by rnelson0** [comment]
Heh, well that will do it!

**Comment by baurmatt** [comment]
Thanks! :)
