### ISSUE TITLE
Syntax error causes 'Whoops!'

### ISSUE THREAD

**Issue by bitfield** [rodjek/puppet-lint#740]
As you can see, the hash of options to `epp` is not closed, and the Puppet parser reports:
```
Error: Could not parse for environment production: Syntax error at ')' at s3cfg.pp:17:5
```

`puppet-lint` says:

Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.2.1
ruby version: 2.4.1-p111
platform: x86_64-darwin15
file path: modules/profile/manifests/s3cfg.pp
file contents:
```
# Deploy S3 credentials
class profile::s3cfg {
  include repo::epel

  ensure_packages('s3cmd',
    {
      'ensure'  => 'installed',
      'require' => Class['repo::epel'],
    }
  )

  file { '/root/.s3cfg':
    content => epp('admin/s3cfg.epp',
      {
        'aws_access_key_id' => lookup('aws_access_key_id', String),
        'aws_secret_key'    => lookup('aws_secret_key', String),
    ),
    owner   => 'root',
  }
}

```
error:
```
NoMethodError: undefined method `next_token' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/lexer/token.rb:180:in `find_token_of'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/lexer/token.rb:122:in `next_token_of'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/data.rb:115:in `block in resource_indexes'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/data.rb:111:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/data.rb:111:in `resource_indexes'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checkplugin.rb:74:in `resource_indexes'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/plugins/check_conditionals.rb:7:in `check'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checkplugin.rb:21:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:58:in `block in run'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:56:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/checks.rb:56:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint.rb:191:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/bin.rb:59:in `block in run'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/bin.rb:56:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/lib/puppet-lint/bin.rb:56:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/puppet-lint-2.2.1/bin/puppet-lint:7:in `<top (required)>'
/usr/local/bin/puppet-lint:22:in `load'
/usr/local/bin/puppet-lint:22:in `<main>'
```

**Comment by rnelson0** [comment]
@bitfield I suspect this does not pass puppet parser validate, but I am unable to verify on a computer. If that is the case, we have a goal to better handle this in v3.0. If it passes the validator, we can dig into it further. Please let us know if it passes, if you can.
