### ISSUE TITLE
ArgumentError: bad value for range

### ISSUE THREAD

**Issue by c22** [rodjek/puppet-lint#741]
puppet-lint seems to be having issues parsing external puppet modules listed in my Puppetfile.

puppet-lint used to handle these just fine, so it could have been a recent change.

---
puppet-lint version: 2.3.0
ruby version: 2.4.1-p111
platform: x86_64-darwin16
file path: Puppetfile
file contents:
```
forge 'forge.puppetlabs.com'

mod 'profile',
  :git => 'ssh://git@[REDACTED].git'
mod 'role',
  :git => 'ssh://git@[REDACTED].git'

```
error:
```
ArgumentError: bad value for range
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/data.rb:121:in `block in resource_indexes'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/data.rb:111:in `each'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/data.rb:111:in `resource_indexes'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:74:in `resource_indexes'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_conditionals/selector_inside_resource.rb:7:in `check'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:21:in `run'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:58:in `block in run'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `each'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `run'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:191:in `run'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:61:in `block in run'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `each'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `run'
/Users/c22/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/bin/puppet-lint:7:in `<top (required)>'
/Users/c22/.rbenv/versions/2.4.1/bin/puppet-lint:22:in `load'
/Users/c22/.rbenv/versions/2.4.1/bin/puppet-lint:22:in `<main>'
```

**Comment by rodjek** [comment]
`Puppetfile` is a Ruby file, not a Puppet manifest and so isn't supported by puppet-lint. If you want to do style checking on it, I'd suggest using [rubocop](https://github.com/bbatsov/rubocop).
