### ISSUE TITLE
Whoops, not sure why. ArgumentError: bad value for range

### ISSUE THREAD

**Issue by davidoae** [rodjek/puppet-lint#742]
puppet-lint version: 2.3.0
ruby version: 2.3.1-p112
platform: x86_64-linux-gnu
file path: puppet-hilary//modules/oaeservice/manifests/nagios/syslog.pp
file contents:
```
class oaeservice::nagios::syslog::server:: {
    Class['::nagios::client'] -> Class['::oaeservice::nagios::syslog::client']


}

```
error:
```
ArgumentError: bad value for range
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/data.rb:121:in `block in resource_indexes'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/data.rb:111:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/data.rb:111:in `resource_indexes'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:74:in `resource_indexes'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_resources/file_mode.rb:13:in `check'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:21:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:58:in `block in run'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:191:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:61:in `block in run'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/puppet-lint-2.3.0/bin/puppet-lint:7:in `<main>'
```

**Comment by rodjek** [comment]
This is due to a syntax error in your manifest (the trailing `::` in the class name on line 1). Class names must match this regex `\A([a-z][a-z0-9_]*)?(::[a-z][a-z0-9_]*)*\Z` (see [the documentation](https://docs.puppet.com/puppet/5.1/lang_reserved.html#classes-and-defined-resource-types)).

```
asmodean :0: code/puppet-lint (git:master → origin)$ puppet parser validate 742.pp
Error: Could not parse for environment production: Illegal fully qualified name at /home/tsharpe/code/puppet-lint/742.pp:1:43
```
