### ISSUE TITLE
puppet-lint has encountered an error that it doesn't know how to handle

### ISSUE THREAD

**Issue by amateo** [rodjek/puppet-lint#750]
I have this output running puppet-lint:
Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.3.0
ruby version: 2.3.1-p112
platform: x86_64-linux-gnu
file path: manifests/profile/manifests/mongodb.pp
file contents:
```
# Class: profile::mongodb
#
# Módulo que se encarga de realizar la configuración de mongodb
#
# Parameters: none
#
# Actions:
#
# Requires: see Modulefile
#
# Sample Usage:
#
class profile::mongodb (
  Array $databases = [],
  Optional[String] $replica_set = undef,
) {
  contain ::mongodb

  #
  # Monitorización
  #
  ensure_packages('python-pymongo')

  nrpe::plugin {'check_mongodb':
    plugin => 'check_mongodb.py',
    args   => '-H localhost -D $ARG1$',
  }

  profile::nagios::service {"${facts[nagios_hostname]} mongodb connect":
    options => {
      service_description => 'MongoDB Connect',
      check_command       => 'check_nrpe!check_mongodb!"-A connect"',
    },
  }

  profile::nagios::service {"${facts[nagios_hostname]} mongodb connections":
    options => {
      service_description => 'MongoDB Connections',
      check_command       => 'check_nrpe!check_mongodb!"-A connections"',
    },
  }

  if $replica_set {
    profile::nagios::service {"${facts[nagios_hostname]} mongodb replica primary":
      options => {
        service_description => 'MongoDB Replica Primary',
        check_command       => "check_nrpe!check_mongodb!\"-A replica_primary -r ${replica_set}\"",
      },
    }

    profile::nagios::service {"${facts[nagios_hostname]} mongodb replica state":
      options => {
        service_description => 'MongoDB Replica State',
        check_command       => "check_nrpe!check_mongodb!\"-A replset_state\"",
      },
    }

    profile::nagios::service {"${facts[nagios_hostname]} mongodb replication lag":
      options => {
        service_description => 'MongoDB Replication Lag',
        check_command       => "check_nrpe!check_mongodb!\"-A replication_lag -h ${facts[networking][ip]}\"",
      },
    }
  }

  profile::nagios::service {"${facts[nagios_hostname]} mongodb number queries":
    options => {
      service_description => 'MongoDB Number Queries',
      check_command       => 'check_nrpe!check_mongodb!"-A queries_per_second -q query"',
    },
  }

  profile::nagios::service {"${facts[nagios_hostname]} mongodb number updates":
    options => {
      service_description => 'MongoDB Number Updates',
      check_command       => 'check_nrpe!check_mongodb!"-A queries_per_second -q update"',
    },
  }

  profile::nagios::service {"${facts[nagios_hostname]} mongodb connect primary":
    options => {
      service_description => 'MongoDB Primary Connection',
      check_command       => "check_nrpe!check_mongodb!\"-A connect_primary\"",
    },
  }

  profile::nagios::service {"${facts[nagios_hostname]} mongodb memory":
    options => {
      service_description => 'MongoDB Memory',
      check_command       => "check_nrpe!check_mongodb!\"-A memory\"",
    },
  }

  profile::nagios::service {"${facts[nagios_hostname]} mongodb lock":
    options => {
      service_description => 'MongoDB Lock Time',
      check_command       => "check_nrpe!check_mongodb!\"-A lock\"",
    },
  }

  profile::nagios::service {"${facts[nagios_hostname]} mongodb index miss ratio":
    options => {
      service_description => 'MongoDB Index Miss Ratio',
      check_command       => "check_nrpe!check_mongodb!\"-A index_miss_ratio\"",
    },
  }

  $databases.each |$db| {
    profile::nagios::service {"${facts[nagios_hostname]} mongodb database size ${db}":
      options => {
        service_description => "MongoDB Database Size: ${db}",
        check_command       => "check_nrpe!check_mongodb!\"-A database_size -d ${db}\"",
      },
    }

    profile::nagios::service {"${facts[nagios_hostname]} mongodb database indexes size ${db}":
      options => {
        service_description => "MongoDB Database Indexes Size: ${db}",
        check_command       => "check_nrpe!check_mongodb!\"-A database_indexes -d ${db}\"",
      },
    }
  }
}

```
error:
```
NoMethodError: undefined method `[]' for nil:NilClass
/var/lib/gems/2.3.0/gems/puppet-lint-legacy_facts-check-0.0.2/lib/puppet-lint/plugins/legacy_facts.rb:91:in `block in check'
/var/lib/gems/2.3.0/gems/puppet-lint-legacy_facts-check-0.0.2/lib/puppet-lint/plugins/legacy_facts.rb:86:in `each'
/var/lib/gems/2.3.0/gems/puppet-lint-legacy_facts-check-0.0.2/lib/puppet-lint/plugins/legacy_facts.rb:86:in `check'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:21:in `run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:58:in `block in run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `each'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:191:in `run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:61:in `block in run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `each'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.0/bin/puppet-lint:7:in `<top (required)>'
/usr/local/bin/puppet-lint:23:in `load'
/usr/local/bin/puppet-lint:23:in `<main>'
```
Error: styleguide violation in manifests/profile/manifests/mongodb.pp (see above)
Error: 153 styleguide violation(s) found. Commit will be aborted.
Please follow the puppet style guide outlined at:
http://docs.puppetlabs.com/guides/style_guide.html
Error: 1 subhooks failed. Please fix above errors.

**Comment by rodjek** [comment]
@amateo it looks like this error came from a puppet-lint plugin (https://github.com/mmckinst/puppet-lint-legacy_facts-check) so you'll need to report the bug there
