### ISSUE TITLE
It looks like puppet-lint has encountered an error that it doesn't know how to handle

### ISSUE THREAD

**Issue by Dan33l** [rodjek/puppet-lint#768]
The ruby is provided by package puppet-agent-1.10.8-1xenial from puppetlabs repository.

```
Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.3.3
ruby version: 2.1.9-p490
platform: x86_64-linux
file path: manifests/role/wordpress/managecore.pp
file contents:

class app_webphp::role::wordpress::managecore (
  Hash $wpvhosts,
  String $wp_cli,
) {

  $wpvhosts.each | String $_wp_servername , Hash $_wp_settings | {

    # use some defaults if not provided
    $_ensure = $_wp_settings['ensure'] ? {
      Enum['present','absent','latest'] => $_wp_settings['ensure'],
      default => 'present',
    }
    $_user = $_wp_settings['user'] ? {
      String  => $_wp_settings['user'],
      default => "${app_webphp::params::default_wpuser}",
    }
    $_wplocale = $_wp_settings['locale'] ? {
      Pattern['^\w\w_\w\w$'] => $_wp_settings['locale'],
      default                => "${app_webphp::params::default_wplocale}",
    }
    $_dbprefix = $_wp_settings['dbprefix'] ? {
      Pattern['^\w*$'] => $_wp_settings['dbprefix'],
      default          => "${app_webphp::params::default_dbprefix}",
    }

    case $_ensure {
      'present': {

        # download wordpress when a vhost is defined as wordpress

        case $_wplocale {
          'en_US': {
            exec { "${_wp_servername} > Download core":
              command => "${wp_cli} core download",
              cwd     => "${_wp_settings['wproot']}",
              creates => "${_wp_settings['wproot']}/wp-admin",
              user    => "${_user}",
            }
          }
          default: {
            exec { "${_wp_servername} > Download core":
              command => "${wp_cli} core download --locale=${_wplocale}",
              cwd     => "${_wp_settings['wproot']}",
              creates => "${_wp_settings['wproot']}/wp-admin",
              user    => "${_user}",
            }
          }
        }

        # it does not create the database (expected already created)

        exec { "${_wp_servername} > Configure core":
          command => "${wp_cli} core config --dbhost=${_wp_settings['wpdbhost']} --dbname=${_wp_settings['wpdbname']} --dbuser=${_wp_settings['wpdbuser']} --dbpass=${_wp_settings['wpdbpass']} --dbprefix=${_dbprefix} --skip-check --force",
          cwd     => "${_wp_settings['wproot']}",
          creates => "${_wp_settings['wproot']}/wp-config.php",
          user    => "${_user}",
          notify  => Exec['update external fact ll_wordpress'],
        }
        ->
        file_line {"${_wp_servername} > set DB_NAME to ${_wp_settings['wpdbname']}":
          ensure => present,
          path   => "${_wp_settings['wproot']}/wp-config.php",
          line   => "define( 'DB_NAME', '${_wp_settings['wpdbname']}' );",
          match  => '^define\( \'DB_NAME\',',
        }
        ->
        file_line {"${_wp_servername} > set DB_USER to ${_wp_settings['wpdbuser']}":
          ensure => present,
          path   => "${_wp_settings['wproot']}/wp-config.php",
          line   => "define( 'DB_USER', '${_wp_settings['wpdbuser']}' );",
          match  => '^define\( \'DB_USER\',',
        }
        ->
        file_line {"${_wp_servername} > set DB_PASSWORD":
          ensure => present,
          path   => "${_wp_settings['wproot']}/wp-config.php",
          line   => "define( 'DB_PASSWORD', '${_wp_settings['wpdbpass']}' );",
          match  => '^define\( \'DB_PASSWORD\',',
        }
        ->
        file_line {"${_wp_servername} > set DB_HOST to ${_wp_settings['wpdbhost']}":
          ensure => present,
          path   => "${_wp_settings['wproot']}/wp-config.php",
          line   => "define( 'DB_HOST', '${_wp_settings['wpdbhost']}' );",
          match  => '^define\( \'DB_HOST\',',
        }
        ->
        #the database and user with credentials must be already created by other process
        exec { "${_wp_servername} > Create core tables":
          command     => "${wp_cli} core install --url=${_wp_servername} --title=\"${_wp_settings['wptitle']}\" --admin_user=${_wp_settings['wpadminuser']} --admin_password=${_wp_settings['wpadminpasswd']} --admin_email=${_wp_settings['wpadminemail']} --skip-email",
          cwd         => "${_wp_settings['wproot']}",
          user        => "${_user}",
          subscribe   => [Exec["${_wp_servername} > Configure core"],File_line["${_wp_servername} > set DB_NAME to ${_wp_settings['wpdbname']}"],File_line["${_wp_servername} > set DB_USER to ${_wp_settings['wpdbuser']}"],File_line["${_wp_servername} > set DB_PASSWORD"],File_line["${_wp_servername} > set DB_HOST to ${_wp_settings['wpdbhost']}"],],
          refreshonly => true,
          notify  => Exec['update external fact ll_wordpress'],
        }
      }
      'absent': {

        # Ensure that setting wproot is realy a path and not empty
        # elsewhere it will make rm -Rf /* ...
        # The atttribute onlyif should be enougth to not run a killer command.
        # The function assert_type raise error and stop the run.

        $_real_wproot = assert_type(Pattern[/^\/\w*\//], $_wp_settings['wproot'])
        exec { "${_wp_servername} > Erase wordpress":
          command => "rm -Rf ${_real_wproot}/*",
          onlyif  => "test -f ${_real_wproot}/wp-config.php",
          notify  => Exec['update external fact ll_wordpress'],
        }
      }
      'latest': {
        # update wp itself if available
        # then update language if available
        if "${facts['ll_wordpress']["${_wp_servername}"]['core']['update']}" != 'none' {
          case $_wplocale {
            'en_US': {
              exec { "${_wp_servername} > Update core wordpress" :
                command => "${wp_cli} --allow-root --path=${_wp_settings['wproot']} core update",
                user    => "${_user}",
                notify  => Exec['update external fact ll_wordpress'],
              }
            }
            default: {
              exec { "${_wp_servername} > Update core wordpress" :
                command => "${wp_cli} --allow-root --path=${_wp_settings['wproot']} core update --locale=${_wplocale}",
                user    => "${_user}",
                notify  => Exec['update external fact ll_wordpress'],
              }
            }
          }

        }
        if "${facts['ll_wordpress']["${_wp_servername}"]['language']['update']}" != 'none' {
          exec { "${_wp_servername} > Update language" :
            command => "${wp_cli} --allow-root --path=${_wp_settings['wproot']} language core update",
            user    => "${_user}",
            require => Exec["${_wp_servername} > Update core wordpress"],
            notify  => Exec['update external fact ll_wordpress'],
          }
        }
      }
      default: {
        fail("unexpected value ensure parameter must be <present|absent|latest>, got '${_ensure}'")
      }
    }

  }
}


error:

TypeError: no implicit conversion of nil into String
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer.rb:319:in `+'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer.rb:319:in `slurp_string'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer.rb:224:in `tokenise'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer.rb:471:in `interpolate_string'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer.rb:226:in `tokenise'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:25:in `load_data'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:55:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint.rb:196:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/tasks/puppet-lint.rb:83:in `block (3 levels) in define'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/tasks/puppet-lint.rb:81:in `each'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/tasks/puppet-lint.rb:81:in `block (2 levels) in define'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/file_utils_ext.rb:58:in `verbose'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/tasks/puppet-lint.rb:75:in `block in define'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:236:in `call'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:236:in `block in execute'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:231:in `each'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:231:in `execute'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:175:in `block in invoke_with_call_chain'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:168:in `invoke_with_call_chain'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:161:in `invoke'
/opt/modules/app_webphp/Rakefile:32:in `block (2 levels) in <top (required)>'
/opt/modules/app_webphp/Rakefile:31:in `each'
/opt/modules/app_webphp/Rakefile:31:in `block in <top (required)>'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:236:in `call'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:236:in `block in execute'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:231:in `each'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:231:in `execute'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:175:in `block in invoke_with_call_chain'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:168:in `invoke_with_call_chain'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/task.rb:161:in `invoke'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:149:in `invoke_task'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:106:in `each'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:106:in `block in top_level'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:115:in `run_with_threads'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:100:in `top_level'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:78:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:75:in `run'
/opt/puppetlabs/puppet/bin/rake:33:in `<main>'

```

**Comment by rodjek** [comment]
Fixed by #846
