### ISSUE TITLE
New way to do hiera_include() with lookup() is broken

### ISSUE THREAD

**Issue by ghoneycutt** [rodjek/puppet-lint#780]
https://puppet.com/docs/puppet/5.0/hiera_migrate_functions.html specifies the code below to use instead of `hiera_include()`. I checked the other lookup calls and this is the only one that fails.

puppet-lint version: 2.3.3
ruby version: 2.1.9-p490
platform: x86_64-darwin16.0
file path: foo.pp
file contents:
```
lookup('classes', {merge => unique}).include

```
error:
```
NoMethodError: undefined method `type' for nil:NilClass
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-absolute_classname-check-0.2.4/lib/puppet-lint/plugins/check_absolute_classname.rb:6:in `block in check'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-absolute_classname-check-0.2.4/lib/puppet-lint/plugins/check_absolute_classname.rb:3:in `each'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-absolute_classname-check-0.2.4/lib/puppet-lint/plugins/check_absolute_classname.rb:3:in `each_with_index'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-absolute_classname-check-0.2.4/lib/puppet-lint/plugins/check_absolute_classname.rb:3:in `check'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:21:in `run'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:60:in `block in run'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `each'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `run'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-2.3.3/lib/puppet-lint.rb:196:in `run'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:59:in `block in run'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `each'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `run'
/Users/gh/.rvm/gems/ruby-2.1.9/gems/puppet-lint-2.3.3/bin/puppet-lint:7:in `<top (required)>'
/Users/gh/.rvm/gems/ruby-2.1.9/bin/puppet-lint:23:in `load'
/Users/gh/.rvm/gems/ruby-2.1.9/bin/puppet-lint:23:in `<main>'
/Users/gh/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:15:in `eval'
/Users/gh/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rodjek** [comment]
@ghoneycutt from the looks of the stack trace, that bug is in a [separate plugin](https://github.com/voxpupuli/puppet-lint-absolute_classname-check) so you'll probably want to move this over over there

**Comment by rodjek** [comment]
Specifically [this line](https://github.com/voxpupuli/puppet-lint-absolute_classname-check/blob/96c83dd2e986d23386ea52652ed5727ebe30a2f9/lib/puppet-lint/plugins/check_absolute_classname.rb#L5). The check is written to always expect there to be something after an `include` (which there isn't in this case). Adding a line like `next if s.nil?` between lines 5 & 6 would probably do the trick.

**Comment by ghoneycutt** [comment]
Thank @rodjek !!

**Comment by jeffmccune** [comment]
For posterity, patch submitted at https://github.com/voxpupuli/puppet-lint-absolute_classname-check/pull/14
