### ISSUE TITLE
Crash report, reason unclear

### ISSUE THREAD

**Issue by flyinbutrs** [rodjek/puppet-lint#781]
---
puppet-lint version: 2.3.3
ruby version: 2.3.0-p0
platform: x86_64-darwin14
file path: manifests/install.pp
file contents:
```
# == Class: consul::install
# Installs consul and needed conf files
class consul::install inherits consul {
    $s3_binary_url = "${consul_dist_url}/${package_version}/consul_${package_version}_${binary_zip_name}"
    $tmp_binary_zip = "/tmp/consul.zip"

    package { 'ensure-jq-installed':
        name    => 'jq',
        ensure  => installed,
    }

    package { 'ensure-pycrypto-installed':
        name    => 'python-crypto',
        ensure  => installed,
    }

    package { 'boto3':
        ensure   => 'latest',
        provider => 'pip',
    }

    group { $consul_group:
        ensure => present,
        system => true,
    }

    user { $consul_user:
        ensure => present,
        system => true,
        gid    => $consul_group,
    }

    file { $config_dir:
        ensure => 'directory',
        owner  => $consul_user,
        group  => $consul_group,
        mode   => '0755',
    }

    file { [$content_dir, $data_dir]:
        ensure => 'directory',
        owner  => $consul_user,
        group  => $consul_group,
        mode   => '0755',
    }

    file { $log_dir:
        ensure => 'directory',
        owner  => $consul_user,
        group  => $consul_group,
        mode   => '0755',
    }->
    file { $log_file:
        ensure => present,
        owner  => $consul_user,
        group  => $consul_group,
        mode   => '0644',
    }

    exec { 'download consul':
        command => "/usr/bin/wget ${s3_binary_url} -O ${tmp_binary_zip}",
    }->
    exec { 'unzip consul':
        cwd     => $bin_dir,
        command => "/usr/bin/unzip ${tmp_binary_zip} -d ${bin_dir}",
        returns => [0, 9],
        creates => "${bin_dir}/consul", # Don't run if file already exists.
    }->
    file { $tmp_binary_zip:
        ensure => absent,
    }

    file { '/usr/local/bin/s3_get_enc_object.py':
        source => 'puppet:///modules/consul/s3_get_enc_object.py',
        owner  => 'root',
        group  => 'root',
        mode   => '0755',
    }

    file { '/usr/local/bin/s3_put_enc_object.py':
        source => 'puppet:///modules/consul/s3_put_enc_object.py',
        owner  => 'root',
        group  => 'root',
        mode   => '0755',
    }
}

```
error:
```
NoMethodError: undefined method `next_token' for nil:NilClass
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer/token.rb:196:in `find_token_of'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer/token.rb:142:in `next_token_of'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/data.rb:176:in `block in resource_indexes'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/data.rb:171:in `each'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/data.rb:171:in `resource_indexes'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:81:in `resource_indexes'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/plugins/check_resources/ensure_first_param.rb:8:in `check'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:21:in `run'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:60:in `block in run'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `each'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `run'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint.rb:196:in `run'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:59:in `block in run'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `each'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `run'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/gems/puppet-lint-2.3.3/bin/puppet-lint:7:in `<top (required)>'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/bin/puppet-lint:23:in `load'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/bin/puppet-lint:23:in `<main>'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/flyinbutrs/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rodjek** [comment]
@flyinbutrs Can you upload that manifest file to this issue? I'm unable to reproduce the problem locally which makes me think it is related to character encoding.

**Comment by flyinbutrs** [comment]
Hi @rodjek,

You can download it here:

https://raw.githubusercontent.com/Nike-Inc/cerberus-consul-puppet-module/master/manifests/install.pp

Thanks,

-Dan
