### ISSUE TITLE
NoMethodError: undefined method `next_token=' for nil:NilClass

### ISSUE THREAD

**Issue by andir** [rodjek/puppet-lint#785]
When running `puppet-lint` on my code base I get the following error that I am supposed to report here:

---
puppet-lint version: 2.3.3
ruby version: 2.3.5-p376
platform: x86_64-linux
file path: manifests/error.pp
file contents:
```
class this_triggers_nilclass {

  include bar

  package{ 'foo':
    name=>"bar",
    ensure => latest,
  }

}

```
error:
```
NoMethodError: undefined method `next_token=' for nil:NilClass
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/plugins/check_whitespace/trailing_whitespace.rb:25:in `fix'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:42:in `block in fix_problems'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:38:in `each'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:38:in `fix_problems'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:63:in `block in run'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `each'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `run'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint.rb:196:in `run'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/tasks/puppet-lint.rb:83:in `block (3 levels) in define'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/tasks/puppet-lint.rb:81:in `each'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/tasks/puppet-lint.rb:81:in `block (2 levels) in define'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/file_utils_ext.rb:59:in `verbose'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/tasks/puppet-lint.rb:75:in `block in define'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:251:in `block in execute'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:251:in `each'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:251:in `execute'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/nix/store/9xf04b239s2sm1qbrzqi2j835bx214xp-ruby-2.3.5/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:181:in `invoke'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:160:in `invoke_task'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:116:in `each'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:116:in `block in top_level'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:125:in `run_with_threads'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:110:in `top_level'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:83:in `block in run'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:80:in `run'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/home/andi/dev/example/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<top (required)>'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/bin/bundle:18:in `load'
/nix/store/cyfyl6jw43j2z7gdrdw1nfh6gjihps4d-bundler-1.14.6/bin/bundle:18:in `<main>'

**Comment by rnelson0** [comment]
@andir Can you check the encoding you are using, or for non-printing characters? I do not receive any errors by copying and pasting your manifest from github, which frequently strips those out.

**Comment by keur** [comment]
This does not trigger an error.

**Comment by rodjek** [comment]
Closing due to inactivity
