### ISSUE TITLE
Error with --fix when no whitespace before hashrocket in resource attribute list

### ISSUE THREAD

**Issue by jessereynolds** [rodjek/puppet-lint#798]
The `--fix` option is crashing when there's no whitespace before a hashrocket in a resource attribute list... 

```
$ puppet-lint --fix /tmp/d.pp
Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
```

---
puppet-lint version: 2.3.3
ruby version: 2.4.0-p0
platform: x86_64-darwin16
file path: /tmp/d.pp
file contents:
```
file { 'a':
   foo => 'foo',
   bar=> 'bar',
}


```
error:
```
NoMethodError: undefined method `next_token=' for nil:NilClass
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/plugins/check_whitespace/trailing_whitespace.rb:25:in `fix'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:42:in `block in fix_problems'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:38:in `each'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:38:in `fix_problems'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:63:in `block in run'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `each'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `run'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint.rb:196:in `run'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:59:in `block in run'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `each'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `run'
/Users/jesse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.3/bin/puppet-lint:7:in `<top (required)>'
/Users/jesse/.rbenv/versions/2.4.0/bin/puppet-lint:22:in `load'
/Users/jesse/.rbenv/versions/2.4.0/bin/puppet-lint:22:in `<main>'
```

**Comment by jessereynolds** [comment]
If I put a space back in there on line 3 then `puppet-lint --fix /tmp/d.pp` yields:

```
$ puppet-lint --fix /tmp/d.pp
ERROR: two-space soft tabs not used on line 2
ERROR: two-space soft tabs not used on line 3
```

**Comment by natemccurdy** [comment]
@jessereynolds Wow, good find. This was bugging me, and I couldn't figure out what was causing it to crash.

Can confirm that this is happening on puppet-lint version 2.3.3.

**Comment by hferrag** [comment]
Also for me, happened on puppet-lint version 2.3.3 on Windows.
