### ISSUE TITLE
Bad value for range

### ISSUE THREAD

**Issue by bahner** [rodjek/puppet-lint#801]
Puppet-lint told me to open an issue for this. I can't see myself, what is wrong here. Seems pretty simple to me.

---
puppet-lint version: 2.3.3
ruby version: 2.3.6-p384
platform: x86_64-linux-gnu
file path: manifests/mailman/nkk.pp
file contents:
```
# point puppet to config files
class profiles::mailman:nkk {

  include inonit::nkk::mailman  
  include profiles::docker::compose

}

```
error:
```
ArgumentError: bad value for range
/usr/lib/ruby/vendor_ruby/puppet-lint/data.rb:182:in `block in resource_indexes'
/usr/lib/ruby/vendor_ruby/puppet-lint/data.rb:171:in `each'
/usr/lib/ruby/vendor_ruby/puppet-lint/data.rb:171:in `resource_indexes'
/usr/lib/ruby/vendor_ruby/puppet-lint/checkplugin.rb:81:in `resource_indexes'
/usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_resources/file_mode.rb:13:in `check'
/usr/lib/ruby/vendor_ruby/puppet-lint/checkplugin.rb:21:in `run'
/usr/lib/ruby/vendor_ruby/puppet-lint/checks.rb:60:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet-lint/checks.rb:57:in `each'
/usr/lib/ruby/vendor_ruby/puppet-lint/checks.rb:57:in `run'
/usr/lib/ruby/vendor_ruby/puppet-lint.rb:196:in `run'
/usr/lib/ruby/vendor_ruby/puppet-lint/bin.rb:59:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet-lint/bin.rb:56:in `each'
/usr/lib/ruby/vendor_ruby/puppet-lint/bin.rb:56:in `run'
/usr/bin/puppet-lint:7:in `<main>'
```

**Comment by bahner** [comment]
Ah, issue was obvious when the eyes focused. A syntax error in class name - missing a colon. Closing issue as bogus. My bad.

**Comment by bahner** [comment]
On the other hand: puppet-lint should probably have catched this .... :-)
