### ISSUE TITLE
v2.3.4 breakage - 'wrong number of arguments' when using Rake task

### ISSUE THREAD

**Issue by fatmcgav** [rodjek/puppet-lint#812]
As part of our CI pipeline, we automatically pull in latest gem versions.

Puppet-lint v2.3.4 seems to have broken the Lint rake task, and therefore our CI tests. 
The error we're seeing is:
```
rake aborted!
ArgumentError: wrong number of arguments (0 for 1)
/var/lib/jenkins/.rvm/gems/ruby-2.1.9@tlsvc/gems/puppet-lint-2.3.4/lib/puppet-lint/optparser.rb:20:in `build'
/var/lib/jenkins/.rvm/gems/ruby-2.1.9@tlsvc/gems/puppet-lint-2.3.4/lib/puppet-lint/tasks/puppet-lint.rb:56:in `block in define'
/var/lib/jenkins/.rvm/gems/ruby-2.1.9@tlsvc/bin/ruby_executable_hooks:15:in `eval'
/var/lib/jenkins/.rvm/gems/ruby-2.1.9@tlsvc/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => lint
(See full trace by running task with --trace)
```

Edit: It looks like 2.3.4 has been yanked from RubyGems.org, so I'm guessing the issue has been spotted...

**Comment by fatmcgav** [comment]
#811 seems to be an attempt to fix this. Thanks @reist
