### ISSUE TITLE
Lexer exception

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [rodjek/puppet-lint#821]
---
puppet-lint version: 2.3.5
ruby version: 2.4.3-p205
platform: x86_64-linux
file path: test.pp
file contents:
```
        file { "${::foo}/dashboards/${dir}/ssi/${file}.${parameter}.json":
                ensure  => present,
                content => "\"continent\": ${to_json_pretty($locations.map |$location| {
                        [upcase($location), {
                                'continent'         => $location,
                                'continent-servers' => "{${query_nodes("(${query}) and location='${location}'", 'hostname').map |$host| { zeroalign_host($host) }.sort.join(',')}}",
                                'continent-nice'    => upcase($location),
                        }]
                }.slice(2).reduce({}) |Hash $memo, Array $pair| {
                        $memo + $pair
                }.filter |$k, $v| {
                        $v['continent-servers'] != '{}'
                })}",
        }

```
error:
```
TypeError: no implicit conversion of nil into String
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/lexer.rb:321:in `+'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/lexer.rb:321:in `slurp_string'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/lexer.rb:226:in `tokenise'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/lexer.rb:473:in `interpolate_string'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/lexer.rb:228:in `tokenise'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/checks.rb:25:in `load_data'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/checks.rb:55:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint.rb:205:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/bin.rb:66:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/bin.rb:62:in `each'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/lib/puppet-lint/bin.rb:62:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.5/bin/puppet-lint:7:in `<top (required)>'
/opt/puppetlabs/puppet/bin/puppet-lint:23:in `load'
/opt/puppetlabs/puppet/bin/puppet-lint:23:in `<main>'
```

I'm not sure, but I think it's because this string is spread across multiple lines.

**Comment by rodjek** [comment]
Fixed by #846
