### ISSUE TITLE
Whoops! It looks like puppet-lint has encountered an error that it doesn't

### ISSUE THREAD

**Issue by bluecmd** [rodjek/puppet-lint#839]
Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.3.6
ruby version: 2.3.1-p112
platform: x86_64-linux-gnu
file path: modules//dhmon/manifests/prometheus.pp
file contents:
```
# Copyright 2018 dhtech
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file
#
# == Class: dhmon::prometheus
#
# Prometheus metrics collector
#
# === Parameters
#
# [*scrape_configs*]
#   Map of the same structure as Prometheus' scrape_configs.
#

class dhmon::prometheus ($scrape_configs) {

  #Create user/group for Prometheus
  group { 'prometheus':
    ensure => 'present',
  }->
  user { 'prometheus':
   ensure => 'present',
   system => true,
  }->
  #Create directories for prometheus and metric storage
  file { '/opt/prometheus':
   ensure => 'directory',
   owner  => 'prometheus',
   group  => 'prometheus',
   mode   => '0700',
  }->
  file { '/srv/metrics':
    content  => template('dhmon/prometheus.yaml.erb'),
    ensure   => directory,
    owner    => 'prometheus',
    group    => 'prometheus',
    mode     => '0700',
  }->

  #Copy prometheus tar bundle to the server
  file { '/tmp/prometheus.tar.gz':
    source  => 'puppet:///data/prometheus-2.3.0.linux-amd64.tar.gz',
    ensure  => file,
    notify  => Exec[ 'untar-prometheus' ],
  }
  #Unpackage prometheus
  exec { 'untar-prometheus':
    command     => '/bin/tar -zxf /tmp/prometheus.tar.gz -C /opt/prometheus --strip-components=1',
    refreshonly => true,
    user        => 'prometheus',
  }

  file { '/opt/prometheus/prometheus.yml':
    content  => template('dhmon/prometheus.yaml.erb'),
    ensure   => file,
    notify   => Exec['prometheus-hup'],
  }->

  file { '/etc/systemd/system/prometheus.service':
    content => template('dhmon/prometheus.service.erb'),
    ensure  => file,
    notify  => Exec["systemctl-daemon-reload"],
  }->

  file { '/etc/default/prometheus':
    content  => template('dhmon/prometheus.default.erb'),
    ensure   => file,
  }->

  file { 'rules':
    path     => '/opt/prometheus/rules',
    ensure   => directory,
    recurse  => true,
    owner    => 'prometheus',
    group    => 'prometheus',
    purge    => true,
    source   => 'puppet:///svn/allevents/dhmon/rules/',
    notify   => Exec['prometheus-hup'],
  }->

  service { 'prometheus':
    ensure  => running,
    require => File["/etc/systemd/system/prometheus.service"]
  }->

  exec { 'systemctl-enable':
    command     => '/bin/systemctl enable prometheus',
    refreshonly => true,
  }

  exec { 'prometheus-hup':
    command     => '/usr/bin/pkill -SIGHUP prometheus',
    refreshonly => true,
  }

  exec { 'systemctl-daemon-reload':
    command     => '/bin/systemctl daemon-reload',
    refreshonly => true,
  }

  apache::proxy { 'prometheus-backend':
    url     => '/prometheus/',
    backend => 'http://localhost:9090/prometheus/',
  }

  file { 'prometheus-presence-exporter':
    path    => '/usr/local/bin/prometheus-presence-exporter',
    ensure  => file,
    source  => 'puppet:///modules/dhmon/prometheus-exporter-presence.py',
  }

  cron { 'prometheus-presence-exporter-cron':
    command => '/usr/local/bin/prometheus-presence-exporter > /var/tmp/export/presence.prom',
    minute  => '*',
    require => [ File['prometheus-presence-exporter'] ],
  }

}

```
error:
```
NoMethodError: undefined method `next_token_of' for nil:NilClass
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/plugins/check_resources/ensure_first_param.rb:31:in `fix'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checkplugin.rb:42:in `block in fix_problems'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checkplugin.rb:38:in `each'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checkplugin.rb:38:in `fix_problems'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:67:in `block in run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:65:in `each'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:65:in `run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint.rb:205:in `run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/bin.rb:66:in `block in run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/bin.rb:62:in `each'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/bin.rb:62:in `run'
/var/lib/gems/2.3.0/gems/puppet-lint-2.3.6/bin/puppet-lint:7:in `<top (required)>'
/usr/local/bin/puppet-lint:23:in `load'
/usr/local/bin/puppet-lint:23:in `<main>'
```

**Comment by rodjek** [comment]
@bluecmd Can you tar up that manifest and attach it to the issue? I'm having trouble reproducing the issue on my end, might be due to a UTF-8 character lost during the copy & paste into the browser.

**Comment by bluecmd** [comment]
Actually, I can give you one better. All these files are available at:
https://github.com/dhtech/puppet-modules/tree/7abd4319293ebe8263a9e26143bac068c5c70534

Run `puppet-lint  --no-puppet_url_without_modules-check --fix modules/` on that and it should crash - it did for me and a co-worker at least.

**Comment by usev6** [comment]
For the record: I wasn't able to reproduce the issue either.
```
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
$ puppet-lint --version
puppet-lint 2.3.6
$ git clone https://github.com/dhtech/puppet-modules.git gh839
$ cd gh839
$ git checkout 7abd4319293ebe8263a9e26143bac068c5c70534
$ puppet-lint --no-puppet_url_without_modules-check --fix modules/
```

There are a lot of WARNING, ERROR and FIXED, but no crash.

Do you have some special settings in your
