### ISSUE TITLE
Whoops! It looks like puppet-lint has encountered an error that it doesn't know how to handle.

### ISSUE THREAD

**Issue by jkroepke** [rodjek/puppet-lint#842]
```
+ bundle exec rake lint
```

Running Puppet 6.0.4 which gives no syntax error.

Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.3.6
ruby version: 2.4.5-p335
platform: x86_64-linux
file path: site/profile/manifests/privoxy.pp
file contents:
```
class profile::privoxy(
  Hash $config = {},
) {
  package { 'privoxy':
    ensure => present;
  }
  file { '/etc/privoxy/config':
    require => Package['privoxy'],
    notify  => Service['privoxy'],
    content => $config.map |$key, $value| { "${key} ${flatten([$value]).join("\n${key} ")}" }.join("\n");
  }
  service { 'privoxy':
    ensure => running,
    enable => true;
  }
}
```
error:
```
TypeError: no implicit conversion of nil into String
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer.rb:321:in `+'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer.rb:321:in `slurp_string'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer.rb:226:in `tokenise'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer.rb:473:in `interpolate_string'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer.rb:228:in `tokenise'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:25:in `load_data'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:55:in `run'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint.rb:205:in `run'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/tasks/puppet-lint.rb:83:in `block (3 levels) in define'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/tasks/puppet-lint.rb:81:in `each'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/tasks/puppet-lint.rb:81:in `block (2 levels) in define'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/file_utils_ext.rb:59:in `verbose'
/usr/local/bundle/gems/puppet-lint-2.3.6/lib/puppet-lint/tasks/puppet-lint.rb:75:in `block in define'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'

**Comment by rodjek** [comment]
Fixed by #846
