### ISSUE TITLE
Type[]] raises NoMethodError

### ISSUE THREAD

**Issue by danielparks** [rodjek/puppet-lint#843]
puppet-lint version: 2.3.6
ruby version: 2.3.5-p376
platform: x86_64-darwin16
file path: test.pp
file contents:
```
define test (
  A[]] $p,
) {
}

```
error:
```
NoMethodError: undefined method `prev_token' for nil:NilClass
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer/token.rb:196:in `find_token_of'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer/token.rb:156:in `prev_token_of'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/plugins/check_classes/parameter_order.rb:44:in `required_parameter?'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/plugins/check_classes/parameter_order.rb:25:in `block (2 levels) in check'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/plugins/check_classes/parameter_order.rb:13:in `each'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/plugins/check_classes/parameter_order.rb:13:in `each_with_index'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/plugins/check_classes/parameter_order.rb:13:in `block in check'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/plugins/check_classes/parameter_order.rb:8:in `each'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/plugins/check_classes/parameter_order.rb:8:in `check'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checkplugin.rb:21:in `run'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:61:in `block in run'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:58:in `each'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:58:in `run'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint.rb:205:in `run'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/bin.rb:66:in `block in run'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/bin.rb:62:in `each'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/bin.rb:62:in `run'
/Users/daniel/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/puppet-lint-2.3.6/bin/puppet-lint:7:in `<top (required)>'
/Users/daniel/.rbenv/versions/2.3.5/bin/puppet-lint:22:in `load'
/Users/daniel/.rbenv/versions/2.3.5/bin/puppet-lint:22:in `<main>'
```

**Comment by rodjek** [comment]
Unhandled exception fixed by #875
