### ISSUE TITLE
First line is empty

### ISSUE THREAD

**Issue by mbevc1** [rodjek/puppet-lint#849]
```
Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.3.6
ruby version: 2.3.8-p459
platform: x86_64-linux
file path: puppet/modules/sf_aws/manifests/sf_aws_asg_maintenance.pp
file contents:

# Install sf-asg-maintenace script.
class sf_aws::sf_aws_asg_maintenance {
    file { '/usr/bin/sf-aws-asg_maintenance':
        ensure  => file,
        owner   => 'root',
        group   => 'root',
        mode    => '0755',
        source  => 'puppet:///modules/sf_aws/sf-aws-asg_maintenance',
        require => Class['::sf_aws::cli'],
    }
}

error:
NoMethodError: undefined method `type' for nil:NilClass
/home/marko/sf/vendor/bundle/ruby/2.3.0/gems/puppet-lint-strict_indent-check-2.0.6/lib/puppet-lint/plugins/check_strict_indent.rb:134:in `block in check'
/home/marko/sf//vendor/bundle/ruby/2.3.0/gems/puppet-lint-strict_indent-check-2.0.6/lib/puppet-lint/plugins/check_strict_indent.rb:49:in `each'
/home/marko/sf//vendor/bundle/ruby/2.3.0/gems/puppet-lint-strict_indent-check-2.0.6/lib/puppet-lint/plugins/check_strict_indent.rb:49:in `check'
/home/marko/sf//vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checkplugin.rb:21:in `run'
/home/marko/sf//vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:61:in `block in run'
/home/marko/sf//vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:58:in `each'
/home/marko/sf//vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:58:in `run'
/home/marko/sf//vendor/bundle/ruby/2.3.0/gems/puppet-lint-2.3.6/lib/puppet-lint.rb:205:in `run'
```

**Comment by rodjek** [comment]
Sorry @mbevc1, this error appears to be coming from a 3rd party plugin (https://github.com/relud/puppet-lint-strict_indent-check) so you'll need to open an issue on that project to fix it up.

**Comment by mbevc1** [comment]
Thanks, I'll open it there :+1:
