### ISSUE TITLE
puppet-lint-class_parameter-check fails on voxpupuli/collectd

### ISSUE THREAD

**Issue by bastelfreak** [rodjek/puppet-lint#926]
Hi!
I just tested https://github.com/ryreitsma/puppet-lint-class_parameter-check/ on the https://github.com/voxpupuli/puppet-collectd module. It creates the following error:

Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.4.2
ruby version: 2.7.1-p83
platform: x86_64-linux
file path: manifests/plugin/mcelog.pp
file contents:
```
# https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_mcelog
class collectd::plugin::mcelog (
  Enum['present', 'absent'] $ensure = 'present',
  # Log file option and memory option are mutualy exclusive.
  Optional[String] $mceloglogfile = undef,
  Optional[Collectd::MCELOG::Memory] $memory = {
    'mcelogclientsocket' => '/var/run/mcelog-client',
    'persistentnotification' => false,
  }
) {

  include collectd

  collectd::plugin { 'mcelog':
    ensure  => $ensure,
    content => epp('collectd/plugin/mcelog.conf.epp', {
      'mceloglogfile' => $mceloglogfile,
      'memory'        => $memory
    }),
  }
}

```
error:
```
NoMethodError: undefined method `value' for nil:NilClass
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-class_parameter-check-0.3.0/lib/model/parameter.rb:20:in `name'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-class_parameter-check-0.3.0/lib/model/parameter_list.rb:35:in `block in validate'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-class_parameter-check-0.3.0/lib/model/parameter_list.rb:32:in `each'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-class_parameter-check-0.3.0/lib/model/parameter_list.rb:32:in `validate'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-class_parameter-check-0.3.0/lib/puppet-lint/plugins/check_class_parameter.rb:12:in `block in check'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-class_parameter-check-0.3.0/lib/puppet-lint/plugins/check_class_parameter.rb:7:in `each'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-class_parameter-check-0.3.0/lib/puppet-lint/plugins/check_class_parameter.rb:7:in `check'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checkplugin.rb:21:in `run'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checks.rb:61:in `block in run'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checks.rb:58:in `each'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checks.rb:58:in `run'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-2.4.2/lib/puppet-lint.rb:205:in `run'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-2.4.2/lib/puppet-lint/tasks/puppet-lint.rb:83:in `block (3 levels) in define'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-2.4.2/lib/puppet-lint/tasks/puppet-lint.rb:81:in `each'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-2.4.2/lib/puppet-lint/tasks/puppet-lint.rb:81:in `block (2 levels) in define'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/file_utils_ext.rb:58:in `verbose'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/puppet-lint-2.4.2/lib/puppet-lint/tasks/puppet-lint.rb:75:in `block in define'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/bin/rake:23:in `load'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-collectd/.vendor/ruby/2.7.0/bin/rake:23:in `<top (required)>'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
```

**Comment by usev6** [comment]
As far as I can see this is not a problem with puppet-lint itself, but with the plugin you mentioned.

A golfed test case seems to be
```
## https://github.com/rodjek/puppet-lint/issues/926
class gh::issue926 (
  $memory = {
    'foo' => true,
  }
) {
}
```

At a first glance, it looks like the plugin doesn't expect the default value for a parameter to be a hash (to be enclosed in curly braces). It sees the comma (within the hash) and takes that for the trailing comma that ends the parameter.
With the following patch to https://github.com/ryreitsma/puppet-lint-class_parameter-check/blob/master/lib/model/parameter_list.rb the crash goes away for me and the plugin still passes its tests.
```
diff --git a/lib/model/parameter_list.rb b/lib/model/parameter_list.rb
index 25b1e6a..bbdd504 100644
--- a/lib/model/parameter_list.rb
+++ b/lib/model/parameter_list.rb
@@ -54,9 +54,9 @@ class ParameterList
     stack = []
 
     @tokens.inject([]) do |memo, token|
-      if [:LBRACK, :LPAREN].include?(token.type)
+      if [:LBRACK, :LPAREN, :LBRACE].include?(token.type)
         stack.push(true)
-      elsif [:RBRACK, :RPAREN].include?(token.type)
+      elsif [:RBRACK, :RPAREN, :RBRACE].include?(token.type)
         stack.pop
       end
 
```

I might be wrong about the cause and about the fix, but I'd recommend to raise an issue over at https://github.com/ryreitsma/puppet-lint-class_parameter-check

**Comment by bastelfreak** [comment]
thanks for your investigation. I raised https://github.com/ryreitsma/puppet-lint-class_parameter-check/issues/24
