### ISSUE TITLE
NoMethodError: undefined method `next_token' for nil:NilClass

### ISSUE THREAD

**Issue by the1sledge** [rodjek/puppet-lint#936]
[
Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.3.6
ruby version: 2.7.2-p137
platform: x86_64-linux
file path: manifests/netperf/redhat.pp
file contents:
```
# Class: profile::netperf::redhat
# ===========================
#
# netperf host configuration module
# manages iperf settings
#
# Authors
# -------
#
# Author Name cmccauley1@udayton.edu
#
# Copyright
# ---------
#
# Copyright 2021 University of Dayton.
#
class profile::netperf::redhat (
  Optional[Integer[0,50]] $swappiness = undef,
  Optional[Integer[0,67108864]] $rmem_max = undef,
  Optional[Integer[0,67108864]] $wmem_max = undef,
  Optional[String] $tcp_rmem = undef,
  Optional[String] $tcp_wmem = undef,
  Optional[Integer[0,1]] $tcp_mtu_probing = undef,
  Optional[String] $default_qdisc = undef,
  Optional[Integer[0,4096]] $somaxconn = undef,
  Optional[Array] $iperf_access_ports = [],
  Optional[Boolean] $sysctl = true,
  Optional[Boolean] $iptables = true,
){
  $_iptables = pick($::iptables, $iptables)
  $_sysctl = pick($::sysctl, $sysctl)
  # service scripts
  systemd::unit_file { 'iperf.service':
    content => epp("${module_name}/netperf/iperf.service.epp",
  }
  ~> service {'iperf':
    enable => true,
  }
  systemd::unit_file { 'iperf3@.service':
    content => epp("${module_name}/netperf/iperf3@.service.epp",
    {
    }),
  }
  ~> service {'iperf3@5200':
    enable => true,
  }
  ~> service {'iperf3@5201':
    enable => true,
  }
  ~> service {'iperf3@5202':
    enable => true,
  }
  ~> service {'iperf3@5203':
    enable => true,
  }
  ~> service {'iperf3@5204':
    enable => true,
  }
  ~> service {'iperf3@5205':
    enable => true,
  }
  ~> service {'iperf3@5206':
    enable => true,
  }
  ~> service {'iperf3@5207':
    enable => true,
  }
  ~> service {'iperf3@5208':
    enable => true,
  }
  ~> service {'iperf3@5209':
    enable => true,
  }
  if $_sysctl {
    sysctl { 'vm.swappiness':
      ensure  => present,
      value   => $swappiness,
      comment => '(default is 60) maintained by Puppet',
    }
    if $rmem_max {
      sysctl { 'net.core.rmem_max':
        ensure  => present,
        value   => $rmem_max,
        comment => 'allow iperf and iperf3 testing with buffers up to 64MB maintained by Puppet',
      }
    }
    if $wmem_max {
      sysctl { 'net.core.wmem_max':
        ensure  => present,
        value   => $wmem_max,
        comment => 'allow iperf and iperf3 testing with buffers up to 64MB maintained by Puppet',
      }
    }
    if $tcp_rmem {
      sysctl { 'net.ipv4.tcp_rmem':
        ensure  => present,
        value   => $tcp_rmem,
        comment => 'increase Linux autotuning TCP buffer limit to 32MB maintained by Puppet',
      }
    }
    if $tcp_wmem {
      sysctl { 'net.ipv4.tcp_wmem':
        ensure  => present,
        value   => $tcp_wmem,
        comment => 'increase Linux autotuning TCP buffer limit to 32MB maintained by Puppet',
      }
    }
    if $tcp_mtu_probing {
      sysctl { 'net.ipv4.tcp_mtu_probing':
        ensure  => present,
        value   => $tcp_mtu_probing,
        comment => 'recommended for hosts with jumbo frames enabled maintained by Puppet',
      }
    }
    if $default_qdisc {
      sysctl { 'net.core.default_qdisc':
        ensure  => present,
        value   => $default_qdisc,
        comment => 'recommended to enable fair queueing maintained by Puppet',
      }
    }
    if $somaxconn {
      sysctl { 'net.core.somaxconn':
        ensure  => present,
        value   => $somaxconn,
        comment => 'Increase kernel socket backlog limit for iperf stability maintained by Puppet',
      }
    }
  }
  if $_iptables {
    firewall_multi { '5001 accept iperf access':
      dport       => $iperf_access_ports,
      proto       => 'tcp',
      action      => 'accept',
    }
  }
}
```
error:
```
NoMethodError: undefined method `next_token' for nil:NilClass
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer/token.rb:196:in `find_token_of'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer/token.rb:142:in `next_token_of'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/data.rb:176:in `block in resource_indexes'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/data.rb:171:in `each'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/data.rb:171:in `resource_indexes'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/checkplugin.rb:81:in `resource_indexes'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/plugins/check_resources/ensure_not_symlink_target.rb:8:in `check'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/checkplugin.rb:21:in `run'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:61:in `block in run'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:58:in `each'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/checks.rb:58:in `run'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint.rb:205:in `run'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/bin.rb:66:in `block in run'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/bin.rb:62:in `each'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/lib/puppet-lint/bin.rb:62:in `run'
/home/cmccauley1/.gem/ruby/gems/puppet-lint-2.3.6/bin/puppet-lint:7:in `<top (required)>'
/home/cmccauley1/bin/puppet-lint:23:in `load'
/home/cmccauley1/bin/puppet-lint:23:in `<main>'
```

**Comment by rodjek** [comment]
Hi @the1sledge,

2.3.6 is quite an old version now and this particular syntax error (you're missing the closing parens on lines 34 & 40) is handled gracefully in the latest version of puppet-lint (2.4.2).

```
0: $ bundle exec puppet-lint 936.pp
ERROR: Syntax error on line 33
Try running `puppet parser validate <file>`

0: $ puppet parser validate 936.pp
Error: Could not parse for environment production: Syntax error at '}' (file: /home/tsharpe/code/rodjek/puppet-lint/936.pp, line: 35, column: 3)
```

**Comment by the1sledge** [comment]
Thanks, I found the missing parens eventually. I will look into updating
the linter. I thought it was being kept up to date automagically.

Regards,
Chuck McCauley
cmccauley@gmail.com
