### ISSUE TITLE
Crash when fixing ensure_first_param

### ISSUE THREAD

**Issue by felixdoerre** [rodjek/puppet-lint#938]
```
Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.4.2
ruby version: 2.5.5-p157
platform: x86_64-linux-gnu
file path: test.pp
file contents:
```
node 'test' {
  
  
  file{'/path':
    target =>'/target',
    ensure => link
  }
}

```
error:
```
NoMethodError: undefined method `next_token_of' for nil:NilClass
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/plugins/check_resources/ensure_first_param.rb:31:in `fix'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checkplugin.rb:42:in `block in fix_problems'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checkplugin.rb:38:in `each'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checkplugin.rb:38:in `fix_problems'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checks.rb:67:in `block in run'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checks.rb:65:in `each'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/checks.rb:65:in `run'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint.rb:205:in `run'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/bin.rb:66:in `block in run'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/bin.rb:62:in `each'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/lib/puppet-lint/bin.rb:62:in `run'
/var/lib/gems/2.5.0/gems/puppet-lint-2.4.2/bin/puppet-lint:7:in `<top (required)>'
/usr/local/bin/puppet-lint:23:in `load'
/usr/local/bin/puppet-lint:23:in `<main>'
```

Compilation exited abnormally with code 1 at Tue Apr  6 01:37:17
```
Please note the two lines with empty spaces in the beginning of the manifest. Without them the error does not occur.

**Comment by felixdoerre** [comment]
Additionally, even without the two empty lines, puppet-lint fails to "--fix" the issue for `ensure_first_param`
